### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@agitator Did you maybe do a forced push to master? I am missing some earlier commits: pull request #6, which partly does the same, was merged to master in July, but the commits are no longer there. And I did a release 1.0.12 to PyPI on 8 August and that commit is also no longer there: the changelog does not mention this release date.

I have changed the settings now, protecting the master branch against forced pushes, just in case.

I could be that I myself did something wrong in August when releasing, forgetting to push. I noticed this earlier, but apparently concluded that it was only one missing commit, which I pushed at the end of August: e995f47ca6e3887f6503298aca72196a9242fca7.

I have the old commits locally, so I can do something about it. Probably it is enough to edit `CHANGES.rst`.

But did you notice anything odd?  Did you use the github UI to merge this or did you do it locally on the command line?

**Comment by agitator** [comment]
@mauritsvanrees was a normal merge on github only
@jensens ?

**Comment by jensens** [comment]
@mauritsvanrees this is strange, I pulled all fresh before I branched away and did not force-push. I'll protect the main branches now. 

I roughly looked over the commits and it seems the current state is clean anyway, or did I miss something?

**Comment by mauritsvanrees** [comment]
`CHANGES.rst` and `setup.py` were missing the 1.0.12 release. I have fixed that in a0604973a04802b8a0d618f2f49ae43f207f0000. Looks good now.

It looks like someone else did a forced push a while ago: I have the same problems in my plone.cachepurging checkouts in coredev 4.3 and 5.0: the local master branch and origin/master branch were in conflict.

Anyway, it's fine now. And the master branch is protected now, so whatever happened cannot happen again. :-)

**Pull request merged**
